### ISSUE TITLE
Cannot download ppc64le binaries

### ISSUE THREAD

**Issue by regiscely** [IBMSpectrumComputing/lsf-kubernetes#1]
I am trying to download IBM Spectrum Computing Cloud Pak Technical Preview. But it seems there is a problem with download link from the following URL  https://epwt-www.mybluemix.net/software/support/trial/cst/programwebsite.wss?siteId=548&h=&tabId=1091&p=

**Comment by mclosson-lsf** [comment]
Hi @regiscely. Thanks for reporting this.  I tried just now and got the following error
```
Error 400: Invalid path /web/prelogin was requested
```

Do you also get this error?

**Comment by regiscely** [comment]
Yes, I get the same error

**Comment by mclosson-lsf** [comment]
Use this temporary link until the main one is repaired.

https://www-01.ibm.com/marketing/iwm/iwm/web/dispatcher.do?source=swerpsw-pak-3

**Comment by mclosson-lsf** [comment]
The main link has been restored.
