### ISSUE TITLE
When submitting job through kubectl(k8s), it doesn't execute properly.

### ISSUE THREAD

**Issue by brlee08** [IBMSpectrumComputing/lsf-kubernetes#2]
Hi,

I refered the "README for IBM Spectrum Computing LSF-Kubernetes Integration, Tech preview" but also the knowledge center guide of LSF Connector for Kubernetes and have tested the same environment.

After all configuration, we've encountered some issues of job submitting. When I submit the job through LSF, it work properly. However, if job is submitted through the Kubernetes, it shows pending/error state and K8S pod terminated. We tried allocate both cpu and gpu resources but doesn't work either. 

Here's the each versions of docker, nvidia-docker, ICP for k8s distribution. Also I attached some logs. 

Is it bug ? Or can I assume any configuration missing ?

[root@lsfsuite log]# nvidia-docker version
NVIDIA Docker: 2.0.3
Client:
Version:           18.09.3
API version:       1.39
Go version:        go1.10.8
Git commit:        774a1f4
Built:             Thu Feb 28 06:33:21 2019
OS/Arch:           linux/amd64
Experimental:      false

Server: Docker Engine - Community
Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:02:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false 

[root@lsfsuite log]# docker -v
Docker version 18.09.3, build 774a1f4

[root@lsfsuite log]# nvidia-docker -v
Docker version 18.09.3, build 774a1f4

[root@lsfsuite log]# kubectl describe daemonset platform-ui -n kube-system |grep  ICP_VERSION
ICP_VERSION:                        3.1.0

[root@lsfsuite log]# kubectl get nodes
NAME         STATUS    ROLES                                 AGE       VERSION

10.0.0.180   Ready     etcd,management,master,proxy,worker   39d       v1.11.1+icp-ee

These are all logs from batch-drive.log. There's nothing inside kubebridge.lsfmaster.log

[lsfadmin@lsfsuite log]$ cat batch-driver.log
Log file created at: 2019/11/27 14:44:12
Running on machine: lsfsuite
Binary: Built with gc go1.11.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W1127 14:44:12.720253   30795 authorization.go:47] Authorization is disabled
W1127 14:44:12.720353   30795 authentication.go:55] Authentication is disabled
I1127 14:44:12.720360   30795 deprecated_insecure_serving.go:49] Serving healthz insecurely on [::]:10501

**Comment by SMark-Black** [comment]
Hi @brlee08  
What version of ICP are you using?  There are some docs here for using GPUs in ICP:  https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.1/manage_applications/deploy_app_gpu.html  You can change the ICP version of the doc to suit your ICP version.  If you are using the OpenShift based version the instructions are a bit different.  That version does not use the nvidia-docker, but it does use the nvidia-device-plugin.  Instructions for that version are here:  https://github.com/zvonkok/origin-ci-gpu/blob/release-3.11/doc/How%20to%20use%20GPUs%20with%20DevicePlugin%20in%20OpenShift%203.11%20.pdf

Mark

**Comment by brlee08** [comment]
Thanks Mark. ICP version I'm using is 3.1.0. I'll try upgrading the version, and test again.

**Comment by SMark-Black** [comment]
We will be coming out with a refreshed tech preview soon.  Can't say when yet.  It will be more robust and the parallel / elastic job support is improved.

If you are using LSF, you can download Service Pack 9 and get all the bits now.

**Comment by SMark-Black** [comment]
Closing this as it's really old
