### ISSUE TITLE
container technology used in LSF and openshift integration

### ISSUE THREAD

**Issue by asm582** [IBMSpectrumComputing/lsf-kubernetes#3]
Hello,

I have read your LSF TP document. it's well written. can you please tell which container technology was used to build container in Openshift environment (Docker or podman?)

**Comment by SMark-Black** [comment]
Hi asm582,

Images are built with docker.

**Comment by asm582** [comment]
ok, thanks @SMark-Black . Have you done any experiments on-prem or on openshit environment running podman by redhat on parallel filesytem like GPFS?

**Comment by SMark-Black** [comment]
@asm582 not that combination.  Are you seeing differences between podman and docker that are of a concern?  If you are using OpenShift or Kubernetes you are abstracted away from that lower layer, at least for most use cases.  If you are looking at an integration of OpenShift and Spectrum Scale, it should be within a storage controller that will process the volume requests, so I don't see where docker/podman come into play except to connect the provided volume.

**Comment by asm582** [comment]
@SMark-Black Yes, I agree. The last I remember podman does not work with parallel filesystem. In our on-prem env, we have a parallel filesystem and we have a desire to use rootless podman. If LSF schedules user jobs as  podman containers, will they run?

**Comment by SMark-Black** [comment]
@asm582 A lot of our users use singularity, then you can just bsub the container directly.  If you look at the LSF Docker integration, it's using these scripts to start/monitor/stop the docker container:
```
EXEC_DRIVER=context[user(lsfadmin)]
            starter[/path/to/serverdir/docker-starter.py]
            controller[/path/to/serverdir/docker-control.py]
            monitor[/path/to/serverdir/docker-monitor.py]
```
These stop the user from being able to use a different UID.  Might be interesting to modify them to call podman instead of docker.  That might do what you want.  Docs are [here.](https://www.ibm.com/support/knowledgecenter/SSWRJV_10.1.0/lsf_welcome/lsf_kc_docker.html)
I have not used podman.  Does it have the same issue of allowing users to run pods with different UIDs, or is it closer to singularity where no additional access is granted?

**Comment by asm582** [comment]
@SMark-Black, Thanks for your reply. rootless podman is close to singularity I believe. Users have UID/GID mappings that help schedule different processes. The same UID/GID mapping is maintained inside the container too.

**Comment by adamsla** [comment]
@asm582, I think 10.1.0.10 includes podman support.  But be forewarned, it's a major patch, and will require the cluster be down.  Not sure about if jobs can be running or not during the upgrade though.  It may require a hard down.  Refer to the release notes after release.

**Comment by asm582** [comment]
Hi @adamsla, good to know there is a podman support. if you have some experiments to share with rootless podman for batch jobs or deeplearning workloads, it would help us.

**Comment by adamsla** [comment]
Maybe @jswelch can chime in.  He's been doing a bunch of LSF + Docker + Multi Node MPI stuff like Tensorflow and Horovod.  He need to increase the RHEL version to 8.2 in his lab to pull it off though.  I suspect it's not too different than what he's been doing already, if not a bit easier.  The biggest deal with MPI is to build it inside the container with the LSF MCA.

**Comment by asm582** [comment]
Thanks @adamsla . 
Hi @jswelch, can you please share your environment configuration. We want to know the filesystem you are using as well as the rootless podman version. If there are any ansible scripts, can you share with us, we are willing to run experiments on our setup. 

also, I would like to know if there a repo where we can collaborate by sharing results.

**Comment by jswelch** [comment]
Hi @asm582 

My lab environments are RHEL 7.X based (with either X86_64 or PPCLE P9) and generally use Spectrum Scale (gpfs).  podman is not supported in LSF 10.1.0.9.  So, not using podman yet.

Below is a LSF article on running the Tensorflow Benchmark in Docker containers across multiple nodes using Horovod on POWER (although I have it working on x86_64 servers just not covered in article).

https://community.ibm.com/community/user/imwuc/blogs/john-welch/2019/12/20/running-tensorflow-benchmark-with-horovod-across-i

**Comment by SMark-Black** [comment]
Closing this as it's just some questions, that were answered.
