### ISSUE TITLE
GPU Resource sharing in LSF

### ISSUE THREAD

**Issue by asm582** [IBMSpectrumComputing/lsf-kubernetes#5]
Hello,
Does LSF allow processes launched by different users to share GPU on a single host? 

Thanks

**Comment by adamsla** [comment]
@asm582, the quick answer is yes, but questions like this are better answered by Google or Duckduck go.  We also have an LSF community forums for answering this.  

You can sign up here: 

https://community.ibm.com/community/user/imwuc/communities/community-home?CommunityKey=74d589b7-7276-4d70-acf5-0fc26430c6c0

Also, using Google, you would have found:

https://www.ibm.com/support/knowledgecenter/SSWRJV_10.1.0/lsf_gpu/chap_submit_monitor_gpu_jobs.html

**Comment by asm582** [comment]
Thank You, closing this issue.
